### ISSUE TITLE
[Bug Report] MySQL CSS row always empty

### ISSUE THREAD

**Issue by rudde0** [MiniaturePets/Issues#321]
# Bug Report

### Technical Information
* Server Software: Purpur 1.19.2
* Plugin Version:  2.8.3 (current latest)
* Dump File: User id 154424, download nonce -773008887, platform PaperMC, version v1_19_R1, source SpigotMC

### General Information

**Bug Description**
Pets are caching properly but there is error with MySQL communication. When I restart the server my selected pet isn't summoning. 
`INSERT IGNORE` and `ON DUPLICATE KEY UPDATE CSS` needed on pet summon event. And CSS row should revamped due to it is empty. Not null, empty. INSERT IGNORE needed because players are able to summon pets once at a time.

**Instructions To Produce**
1. Set up mysql file, for example:
```yaml
useMySQL: true
hostName: 193.164.7.250
port: '3306'
databaseName: ''
username: 
password: 
method: MySQL
autoReconnect: true
useSSL: false
tablePrefix: 'playerPets_'
```
2. Boot server, join and summon the pet with executing command.
3. Restart the server 
4. Pet is gone, MySQL values are appended but CSS is empty.
5. If you repeat the process MySQL value added again instead of updating the old one.

**Logs**
No errors.

**Visual Demonstration**
Spammed mysql inputs and empty CSS field:
https://prnt.sc/2fjVWTa6z2VJ
