### ISSUE TITLE
pets damaging players. using 1.19.3

### ISSUE THREAD

**Issue by noft117** [MiniaturePets/Issues#335]
I am trying to set up vanilla mob mpets, but i notice they are damaging me. They are hostile. is there a way to turn this setting off? i am on 1.19.3 I would also like to add icons to vanilla mobs in the gui. is that possible?  this is what it looks like in the config but it still doesnt show up with the icon either.
```
settings:
  sounds: ZOMBIE
  mobtype: ZOMBIE
  nametagHeight: 0
  displayItem: ZOMBIE_SPAWN_EGG
  permission: mpet.ZOMBIE

skins:
parts:
```
