### ISSUE TITLE
[Feature Request] Revert SkullOwner %PetOwner% placeholder

### ISSUE THREAD

**Issue by rudde0** [MiniaturePets/Issues#344]
# Feature Request

### General Information

**Feature Description**
In head part of armor stands we can't define player head with pet owner placeholder. So MiniMe doesn't working anymore.

Example config:
```
settings:
  Sounds: ''
  Animationspeed: 1
  Animationsmoothness: 5
  Displayitem: symbol
  permission: mpet.miniMe
  Nametagheight: 0.0
parts:
  body:
    mini: true
    visible: true
    upDown: 0
    forwardBackward: 0
    rightLeft: 0
    chestplateItem: 'material:LEATHER_CHESTPLATE color:51;76;178 '
    left_legItem: 'material:LEATHER_LEGGINGS color:0;0;0 '
    boots: 'material:LEATHER_BOOTS color:51;76;178 '
animations:
  '1':
    body:
      left_handPose: 45;0;0
      left_legPose: -45;0;0
      right_legPoes: 45;0;0
      right_handPose: -45;0;0
  '2':
    body:
      left_handPose: 45;0;0
      left_legPose: -45;0;0
      right_legPoes: 45;0;0
      right_handPose: -45;0;0
  '3':
    body:
      left_handPose: -45;0;0
      left_legPose: 45;0;0
      right_legPoes: -45;0;0
      right_handPose: 45;0;0
  '4':
    body:
      left_handPose: 0;0;0
      left_legPose: 0;0;0
      right_legPoes: 0;0;0
      right_handPose: 0;0;0
  '5':
    body:
      left_handPose: -45;0;0
      left_legPose: 45;0;0
      right_legPoes: -45;0;0
      right_handPose: 45;0;0
```
